CREATE TABLE IF NOT EXISTS PRODUCT(
    PRO_ID TEXT PRIMARY KEY,
    PRO_NAME TEXT,
    PRO_PRICE TEXT,
    PRO_COM TEXT,
);
INSERT INTO PRODUCT(PRO_ID,PRO_NAME,PRO_COM,PRO_PRICE)
VALUES
    ("101","Mother Board","3200","15"),
    ("102","DVD player","8900","14"),
    ("103","Keyboard","3100","18"),
    ("104","CD","6200","12"),
    ("105","Desktop","22200","11"),
    ("106","Mouse","1200","10");
SELECT PRO_NAME,PRO_PRICE
    FROM PRODUCT
    WHERE PRO_PRICE = (SELECT MIN(PRO_PRICE) FROM PRODUCT);
SELECT PRO_NAME,PRO_PRICE
    FROM PRODUCT
    WHERE PRO_PRICE = (SELECT MAX(PRO_PRICE) FROM PRODUCT);




